version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      # Add other environment variables here
      # - DATABASE_URL=your_database_url
    volumes:
      # For development, you might want to add:
      # - .:/app
      # - /app/node_modules
      # - /app/.next
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Uncomment and configure if you need a database
  # db:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: your_database
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U your_user -d your_database"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
# volumes:
#   postgres_data:
