version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: agentic-ui-uptime-kuma
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
