services:
  lightrag:
    container_name: agentic-lightrag
    image: ghcr.io/hkuds/lightrag:1.3.10 # 1.3.7 more reliable version than 1.3.8
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   tags:
    #     - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"