services:
  lightrag-mcp:
    image: agentic-ui:lightrag-mcp
    build: .
    ports:
      - "${MCP_PORT:-8000}:8000"
    environment:
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-8000}
    restart: unless-stopped